// <auto-generated />
using System;
using Estately.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estately.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251122220216_InitIdentitySchema")]
    partial class InitIdentitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("UserTypeID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserTypeID");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpAppointmentStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusId");

                    b.ToTable("LkpAppointmentStatus");
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpDocumentType", b =>
                {
                    b.Property<int>("DocumentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DocumentTypeID");

                    b.ToTable("LkpDocumentTypes");
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpPropertyHistoryType", b =>
                {
                    b.Property<int>("HistoryTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("HistoryTypeID");

                    b.ToTable("LkpPropertyHistoryTypes");
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpPropertyStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusID");

                    b.ToTable("LkpPropertyStatus");
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpPropertyType", b =>
                {
                    b.Property<int>("PropertyTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PropertyTypeID");

                    b.ToTable("LkpPropertyTypes");
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpUserType", b =>
                {
                    b.Property<int>("UserTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserTypeID");

                    b.ToTable("LkpUserType");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblAppointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentID"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("EmployeeClientID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.HasKey("AppointmentID");

                    b.HasIndex(new[] { "StatusID" }, "IX_TblAppointments")
                        .IsUnique();

                    b.HasIndex(new[] { "EmployeeClientID" }, "IX_TblAppointments_EmployeeClientID");

                    b.HasIndex(new[] { "PropertyID" }, "IX_TblAppointments_PropertyID");

                    b.ToTable("TblAppointments");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblBranch", b =>
                {
                    b.Property<int>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("BranchID");

                    b.ToTable("TblBranches");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblBranchDepartment", b =>
                {
                    b.Property<int>("BranchDepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchDepartmentID"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.HasKey("BranchDepartmentID");

                    b.HasIndex("BranchID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("TblBranchDepartments");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblCity", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CityID");

                    b.ToTable("TblCities");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblClientProfile", b =>
                {
                    b.Property<int>("ClientProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientProfileID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ClientProfileID");

                    b.HasIndex(new[] { "UserID" }, "IX_TblClientProfiles")
                        .IsUnique();

                    b.ToTable("TblClientProfiles");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblClientPropertyInterest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InterestDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("InterestId");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("PropertyId");

                    b.ToTable("TblClientPropertyInterests");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblDepartment", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DepartmentID");

                    b.ToTable("TblDepartments");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblDeveloperProfile", b =>
                {
                    b.Property<int>("DeveloperProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeveloperProfileID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeveloperName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeveloperTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PortofolioPhoto")
                        .HasMaxLength(800)
                        .IsUnicode(false)
                        .HasColumnType("varchar(800)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteURL")
                        .HasMaxLength(800)
                        .IsUnicode(false)
                        .HasColumnType("varchar(800)");

                    b.HasKey("DeveloperProfileID");

                    b.HasIndex(new[] { "UserID" }, "IX_TblDeveloperProfiles")
                        .IsUnique();

                    b.ToTable("TblDeveloperProfiles");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblEmployee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("BranchDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nationalid")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int?>("ReportsTo")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("BranchDepartmentId");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("ReportsTo");

                    b.HasIndex(new[] { "UserID" }, "IX_TblEmployees")
                        .IsUnique();

                    b.ToTable("TblEmployees");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblEmployeeClient", b =>
                {
                    b.Property<int>("EmployeeClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeClientID"));

                    b.Property<DateTime?>("AssignmentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ClientProfileID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeClientID");

                    b.HasIndex(new[] { "ClientProfileID" }, "IX_TblEmployeeClients_ClientProfileID");

                    b.HasIndex(new[] { "EmployeeID" }, "IX_TblEmployeeClients_EmployeeID");

                    b.ToTable("TblEmployeeClients");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblFavorite", b =>
                {
                    b.Property<int>("FavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteID"));

                    b.Property<int>("ClientProfileID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.HasKey("FavoriteID");

                    b.HasIndex(new[] { "ClientProfileID" }, "IX_TblFavorites_ClientProfileID");

                    b.HasIndex(new[] { "PropertyID" }, "IX_TblFavorites_PropertyID");

                    b.ToTable("TblFavorites");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblJobTitle", b =>
                {
                    b.Property<int>("JobTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTitleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobTitleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("JobTitleId");

                    b.ToTable("TblJobTitles");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblProperty", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("BathsNo")
                        .HasColumnType("int");

                    b.Property<int>("BedsNo")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DeveloperProfileID")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExpectedRentPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("FloorNo")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<DateTime?>("ListingDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("PropertyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PropertyTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("int");

                    b.Property<int>("ZoneID")
                        .HasColumnType("int");

                    b.HasKey("PropertyID");

                    b.HasIndex("AgentId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "PropertyCode" }, "IX_TblProperties_1")
                        .IsUnique();

                    b.HasIndex(new[] { "DeveloperProfileID" }, "IX_TblProperties_DeveloperProfileID");

                    b.HasIndex(new[] { "PropertyTypeID" }, "IX_TblProperties_PropertyTypeID");

                    b.HasIndex(new[] { "ZoneID" }, "IX_TblProperties_ZoneID");

                    b.ToTable("TblProperties");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblPropertyDocument", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<int>("DocumentTypeID")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DocumentID");

                    b.HasIndex("DocumentTypeID");

                    b.HasIndex("PropertyID");

                    b.HasIndex("UserID");

                    b.ToTable("TblPropertyDocuments");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblPropertyFeature", b =>
                {
                    b.Property<int>("FeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("IsAmenity")
                        .HasColumnType("bit");

                    b.HasKey("FeatureID");

                    b.ToTable("TblPropertyFeatures");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblPropertyFeaturesMapping", b =>
                {
                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<int>("FeatureID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PropertyID", "FeatureID");

                    b.HasIndex(new[] { "FeatureID" }, "IX_TblPropertyFeaturesMapping_FeatureID");

                    b.ToTable("TblPropertyFeaturesMapping");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblPropertyHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("HistoryTypeID")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("HistoryID");

                    b.HasIndex("HistoryTypeID");

                    b.HasIndex("PropertyID");

                    b.HasIndex("UserID");

                    b.ToTable("TblPropertyHistory");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblPropertyImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ImageID");

                    b.HasIndex(new[] { "PropertyID" }, "IX_TblPropertyImages_PropertyID");

                    b.ToTable("TblPropertyImages");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblZone", b =>
                {
                    b.Property<int>("ZoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneID"));

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ZoneID");

                    b.HasIndex(new[] { "CityID" }, "IX_TblZones_CityID");

                    b.ToTable("TblZones");
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationRoleClaim", b =>
                {
                    b.HasOne("Estately.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.HasOne("Estately.Core.Entities.LkpUserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationUserClaim", b =>
                {
                    b.HasOne("Estately.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationUserLogin", b =>
                {
                    b.HasOne("Estately.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("Estately.Core.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationUserToken", b =>
                {
                    b.HasOne("Estately.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Estately.Core.Entities.TblAppointment", b =>
                {
                    b.HasOne("Estately.Core.Entities.TblEmployeeClient", "EmployeeClient")
                        .WithMany("TblAppointments")
                        .HasForeignKey("EmployeeClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.TblProperty", "Property")
                        .WithMany("TblAppointments")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.LkpAppointmentStatus", "Status")
                        .WithOne("TblAppointment")
                        .HasForeignKey("Estately.Core.Entities.TblAppointment", "StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeClient");

                    b.Navigation("Property");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblBranchDepartment", b =>
                {
                    b.HasOne("Estately.Core.Entities.TblBranch", "Branch")
                        .WithMany("TblBranchDepartments")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.TblDepartment", "Department")
                        .WithMany("TblBranchDepartments")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblClientProfile", b =>
                {
                    b.HasOne("Estately.Core.Entities.Identity.ApplicationUser", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("Estately.Core.Entities.TblClientProfile", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblClientPropertyInterest", b =>
                {
                    b.HasOne("Estately.Core.Entities.TblClientProfile", "ClientProfile")
                        .WithMany("TblClientPropertyInterests")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.TblProperty", "Property")
                        .WithMany("TblClientPropertyInterests")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblDeveloperProfile", b =>
                {
                    b.HasOne("Estately.Core.Entities.Identity.ApplicationUser", "User")
                        .WithOne("DeveloperProfile")
                        .HasForeignKey("Estately.Core.Entities.TblDeveloperProfile", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblEmployee", b =>
                {
                    b.HasOne("Estately.Core.Entities.TblBranchDepartment", "BranchDepartment")
                        .WithMany("TblEmployees")
                        .HasForeignKey("BranchDepartmentId");

                    b.HasOne("Estately.Core.Entities.TblJobTitle", "JobTitle")
                        .WithMany("TblEmployees")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.TblEmployee", "ReportsToNavigation")
                        .WithMany("InverseReportsToNavigation")
                        .HasForeignKey("ReportsTo");

                    b.HasOne("Estately.Core.Entities.Identity.ApplicationUser", "User")
                        .WithOne("EmployeeProfile")
                        .HasForeignKey("Estately.Core.Entities.TblEmployee", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BranchDepartment");

                    b.Navigation("JobTitle");

                    b.Navigation("ReportsToNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblEmployeeClient", b =>
                {
                    b.HasOne("Estately.Core.Entities.TblClientProfile", "ClientProfile")
                        .WithMany("TblEmployeeClients")
                        .HasForeignKey("ClientProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.TblEmployee", "Employee")
                        .WithMany("TblEmployeeClients")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblFavorite", b =>
                {
                    b.HasOne("Estately.Core.Entities.TblClientProfile", "ClientProfile")
                        .WithMany("TblFavorites")
                        .HasForeignKey("ClientProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.TblProperty", "Property")
                        .WithMany("TblFavorites")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblProperty", b =>
                {
                    b.HasOne("Estately.Core.Entities.TblEmployee", "Agent")
                        .WithMany("TblProperties")
                        .HasForeignKey("AgentId");

                    b.HasOne("Estately.Core.Entities.TblDeveloperProfile", "DeveloperProfile")
                        .WithMany("TblProperties")
                        .HasForeignKey("DeveloperProfileID");

                    b.HasOne("Estately.Core.Entities.LkpPropertyType", "PropertyType")
                        .WithMany("TblProperties")
                        .HasForeignKey("PropertyTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.LkpPropertyStatus", "Status")
                        .WithMany("TblProperties")
                        .HasForeignKey("StatusId");

                    b.HasOne("Estately.Core.Entities.TblZone", "Zone")
                        .WithMany("TblProperties")
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("DeveloperProfile");

                    b.Navigation("PropertyType");

                    b.Navigation("Status");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblPropertyDocument", b =>
                {
                    b.HasOne("Estately.Core.Entities.LkpDocumentType", "DocumentType")
                        .WithMany("TblPropertyDocuments")
                        .HasForeignKey("DocumentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.TblProperty", "Property")
                        .WithMany("TblPropertyDocuments")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.Identity.ApplicationUser", "User")
                        .WithMany("PropertyDocuments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentType");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblPropertyFeaturesMapping", b =>
                {
                    b.HasOne("Estately.Core.Entities.TblPropertyFeature", "Feature")
                        .WithMany("TblPropertyFeaturesMappings")
                        .HasForeignKey("FeatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.TblProperty", "Property")
                        .WithMany("TblPropertyFeaturesMappings")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblPropertyHistory", b =>
                {
                    b.HasOne("Estately.Core.Entities.LkpPropertyHistoryType", "HistoryType")
                        .WithMany("TblPropertyHistories")
                        .HasForeignKey("HistoryTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.TblProperty", "Property")
                        .WithMany("TblPropertyHistories")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estately.Core.Entities.Identity.ApplicationUser", "User")
                        .WithMany("PropertyHistories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HistoryType");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblPropertyImage", b =>
                {
                    b.HasOne("Estately.Core.Entities.TblProperty", "Property")
                        .WithMany("TblPropertyImages")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblZone", b =>
                {
                    b.HasOne("Estately.Core.Entities.TblCity", "City")
                        .WithMany("TblZones")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Estately.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("ClientProfile");

                    b.Navigation("DeveloperProfile");

                    b.Navigation("EmployeeProfile");

                    b.Navigation("PropertyDocuments");

                    b.Navigation("PropertyHistories");
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpAppointmentStatus", b =>
                {
                    b.Navigation("TblAppointment")
                        .IsRequired();
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpDocumentType", b =>
                {
                    b.Navigation("TblPropertyDocuments");
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpPropertyHistoryType", b =>
                {
                    b.Navigation("TblPropertyHistories");
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpPropertyStatus", b =>
                {
                    b.Navigation("TblProperties");
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpPropertyType", b =>
                {
                    b.Navigation("TblProperties");
                });

            modelBuilder.Entity("Estately.Core.Entities.LkpUserType", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblBranch", b =>
                {
                    b.Navigation("TblBranchDepartments");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblBranchDepartment", b =>
                {
                    b.Navigation("TblEmployees");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblCity", b =>
                {
                    b.Navigation("TblZones");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblClientProfile", b =>
                {
                    b.Navigation("TblClientPropertyInterests");

                    b.Navigation("TblEmployeeClients");

                    b.Navigation("TblFavorites");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblDepartment", b =>
                {
                    b.Navigation("TblBranchDepartments");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblDeveloperProfile", b =>
                {
                    b.Navigation("TblProperties");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblEmployee", b =>
                {
                    b.Navigation("InverseReportsToNavigation");

                    b.Navigation("TblEmployeeClients");

                    b.Navigation("TblProperties");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblEmployeeClient", b =>
                {
                    b.Navigation("TblAppointments");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblJobTitle", b =>
                {
                    b.Navigation("TblEmployees");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblProperty", b =>
                {
                    b.Navigation("TblAppointments");

                    b.Navigation("TblClientPropertyInterests");

                    b.Navigation("TblFavorites");

                    b.Navigation("TblPropertyDocuments");

                    b.Navigation("TblPropertyFeaturesMappings");

                    b.Navigation("TblPropertyHistories");

                    b.Navigation("TblPropertyImages");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblPropertyFeature", b =>
                {
                    b.Navigation("TblPropertyFeaturesMappings");
                });

            modelBuilder.Entity("Estately.Core.Entities.TblZone", b =>
                {
                    b.Navigation("TblProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
