// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Estately.Core.Entities
{
    [Table("LkpAppointmentStatus")]
    public partial class LkpAppointmentStatus
    {
        [Key]
        public int StatusId { get; set; }

        public string StatusName { get; set; }

        public string Description { get; set; }

        [InverseProperty("Status")]
        public virtual TblAppointment TblAppointment { get; set; }
    }
}
