// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    [Table("LkpDocumentType")]
    public partial class LkpDocumentType
    {
        [Key]
        public int DocumentTypeID { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        [InverseProperty("DocumentType")]
        public virtual ICollection<TblPropertyDocument> TblPropertyDocuments { get; set; } = new List<TblPropertyDocument>();
    }
}