// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Core.Entities;

[Table("LkpUserType")]
public partial class LkpUserType
{
    [Key]
    public int UserTypeID { get; set; }

    [Required]
    [StringLength(255)]
    public string UserTypeName { get; set; }

    [StringLength(500)]
    public string? Description { get; set; }

    [InverseProperty("UserType")]
    public virtual ICollection<TblUser>? TblUsers { get; set; } = new List<TblUser>();
}
