// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Core.Entities
{
    [Table("LkpUserType")]
    public partial class LkpUserType
    {
        [Key]
        public int UserTypeID { get; set; }

        public string UserTypeName { get; set; }

        public string Description { get; set; }

        [InverseProperty("UserType")]
        public virtual ICollection<TblUser> TblUsers { get; set; } = new List<TblUser>();
    }
}