<<<<<<< HEAD
﻿using System.ComponentModel.DataAnnotations;
=======
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
>>>>>>> dacaf1c709af6da3a4b9637f725e3b87f1c02934
using System.ComponentModel.DataAnnotations.Schema;

namespace Estately.Core.Entities;

[Table("LkpUserType")]
public partial class LkpUserType
{
<<<<<<< HEAD
    [Table("LkpUserType")]
    public class LkpUserType
    {
        [Key]
        public int UserTypeID { get; set; }

        [Required, StringLength(255)]
        public string UserTypeName { get; set; }

        [StringLength(500)]
        public string? Description { get; set; }

        // ONE-TO-MANY (Correct)
        public virtual ICollection<ApplicationUser> Users { get; set; }
            = new List<ApplicationUser>();
    }
=======
    [Key]
    public int UserTypeID { get; set; }

    [Required]
    [StringLength(255)]
    public string UserTypeName { get; set; }

    [StringLength(500)]
    public string? Description { get; set; }

    [InverseProperty("UserType")]
    public virtual ICollection<TblUser>? TblUsers { get; set; } = new List<TblUser>();
>>>>>>> dacaf1c709af6da3a4b9637f725e3b87f1c02934
}
