// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{

    [Index("StatusID", Name = "IX_TblAppointments", IsUnique = true)]
    [Index("EmployeeClientID", Name = "IX_TblAppointments_EmployeeClientID")]
    [Index("PropertyID", Name = "IX_TblAppointments_PropertyID")]
    public partial class TblAppointment
    {
        [Key]
        public int AppointmentID { get; set; }

        public int StatusID { get; set; }

        public int PropertyID { get; set; }

        public int EmployeeClientID { get; set; }

        public DateTime AppointmentDate { get; set; }

        public string Notes { get; set; }

        [ForeignKey("EmployeeClientID")]
        [InverseProperty("TblAppointments")]
        public virtual TblEmployeeClient EmployeeClient { get; set; }

        [ForeignKey("PropertyID")]
        [InverseProperty("TblAppointments")]
        public virtual TblProperty Property { get; set; }

        [ForeignKey("StatusID")]
        [InverseProperty("TblAppointment")]
        public virtual LkpAppointmentStatus Status { get; set; }
    }
}