// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Core.Entities;

public partial class TblBranch
{
    [Key]
    public int BranchID { get; set; }

    public string BranchName { get; set; }

    public string ManagerName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<TblBranchDepartment> TblBranchDepartments { get; set; } = new List<TblBranchDepartment>();
}