// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Estately.Core.Entities
{

    public partial class TblBranchDepartment
    {
        [Key]
        public int BranchDepartmentID { get; set; }

        public int BranchID { get; set; }

        public int DepartmentID { get; set; }

        public DateTime? CreatedAt { get; set; }

        [ForeignKey("BranchID")]
        [InverseProperty("TblBranchDepartments")]
        public virtual TblBranch Branch { get; set; }

        [ForeignKey("DepartmentID")]
        [InverseProperty("TblBranchDepartments")]
        public virtual TblDepartment Department { get; set; }

        [InverseProperty("BranchDepartment")]
        public virtual ICollection<TblEmployee> TblEmployees { get; set; } = new List<TblEmployee>();
    }
}