// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblClientPropertyInterest
    {
        [Key]
        public int InterestId { get; set; }

        public int ClientProfileId { get; set; }

        public int PropertyId { get; set; }

        public DateTime? InterestDate { get; set; }

        public string Notes { get; set; }

        [ForeignKey("ClientProfileId")]
        [InverseProperty("TblClientPropertyInterests")]
        public virtual TblClientProfile ClientProfile { get; set; }

        [ForeignKey("PropertyId")]
        [InverseProperty("TblClientPropertyInterests")]
        public virtual TblProperty Property { get; set; }
    }
}