// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    [Index("UserID", Name = "IX_TblClientProfiles", IsUnique = true)]
    public partial class TblClientProfile
    {
        [Key]
        public int ClientProfileID { get; set; }

        public int UserID { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Phone { get; set; }

        public string Address { get; set; }

        public string ProfilePhoto { get; set; }

        public DateTime? CreatedAt { get; set; }

        [InverseProperty("ClientProfile")]
        public virtual ICollection<TblClientPropertyInterest> TblClientPropertyInterests { get; set; } = new List<TblClientPropertyInterest>();

        [InverseProperty("ClientProfile")]
        public virtual ICollection<TblEmployeeClient> TblEmployeeClients { get; set; } = new List<TblEmployeeClient>();

        [InverseProperty("ClientProfile")]
        public virtual ICollection<TblFavorite> TblFavorites { get; set; } = new List<TblFavorite>();

        [ForeignKey("UserID")]
        [InverseProperty("TblClientProfile")]
        public virtual TblUser User { get; set; }
    }
}