// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblCity
    {
        [Key]
        public int CityID { get; set; }

        public string CityName { get; set; }

        [InverseProperty("City")]
        public virtual ICollection<TblZone> TblZones { get; set; } = new List<TblZone>();
    }
}