// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Core.Entities;

[Index("UserID", Name = "IX_TblDeveloperProfiles", IsUnique = true)]
public partial class TblDeveloperProfile
{
    [Key]
    public int DeveloperProfileID { get; set; }

    public int UserID { get; set; }

    public string DeveloperTitle { get; set; }

    public string DeveloperName { get; set; }

    public string WebsiteURL { get; set; }

    public string PortofolioPhoto { get; set; }

    public string Phone { get; set; }

    public DateTime? CreatedAt { get; set; }

    [InverseProperty("DeveloperProfile")]
    public virtual ICollection<TblProperty> TblProperties { get; set; } = new List<TblProperty>();

    [ForeignKey("UserID")]
    [InverseProperty("TblDeveloperProfile")]
    public virtual TblUser User { get; set; }
}