// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Estately.Core.Entities
{
    public partial class TblDepartment
    {
        [Key]
        public int DepartmentID { get; set; }

        public string DepartmentName { get; set; }

        public string ManagerName { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        public DateTime? CreatedAt { get; set; }

        [InverseProperty("Department")]
        public virtual ICollection<TblBranchDepartment> TblBranchDepartments { get; set; } = new List<TblBranchDepartment>();
    }
}