// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>3
namespace Estately.Core.Entities;

[Index("ClientProfileID", Name = "IX_TblEmployeeClients_ClientProfileID")]
[Index("EmployeeID", Name = "IX_TblEmployeeClients_EmployeeID")]
public partial class TblEmployeeClient
{
    [Key]
    public int EmployeeClientID { get; set; }

    public int EmployeeID { get; set; }

    public int ClientProfileID { get; set; }

    public DateTime? AssignmentDate { get; set; }

    [ForeignKey("ClientProfileID")]
    [InverseProperty("TblEmployeeClients")]
    public virtual TblClientProfile ClientProfile { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("TblEmployeeClients")]
    public virtual TblEmployee Employee { get; set; }

    [InverseProperty("EmployeeClient")]
    public virtual ICollection<TblAppointment> TblAppointments { get; set; } = new List<TblAppointment>();
}