// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    [Index("UserID", Name = "IX_TblEmployees", IsUnique = true)]
    public partial class TblEmployee
    {
        [Key]
        public int EmployeeID { get; set; }

        public int UserID { get; set; }

        public int? BranchDepartmentId { get; set; }

        public int JobTitleId { get; set; }

        public int? ReportsTo { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Gender { get; set; }

        public int Age { get; set; }

        public string Phone { get; set; }

        public string Nationalid { get; set; }

        [NotMapped]
        public byte[] ProfilePhotoBytes { get; set; }

        public string ProfilePhoto { get; set; }

        public decimal Salary { get; set; }

        public DateTime? HireDate { get; set; }

        [ForeignKey("BranchDepartmentId")]
        [InverseProperty("TblEmployees")]
        public virtual TblBranchDepartment BranchDepartment { get; set; }

        [InverseProperty("ReportsToNavigation")]
        public virtual ICollection<TblEmployee> InverseReportsToNavigation { get; set; } = new List<TblEmployee>();

        [ForeignKey("JobTitleId")]
        [InverseProperty("TblEmployees")]
        public virtual TblJobTitle JobTitle { get; set; }

        [ForeignKey("ReportsTo")]
        [InverseProperty("InverseReportsToNavigation")]
        public virtual TblEmployee ReportsToNavigation { get; set; }

        [InverseProperty("Employee")]
        public virtual ICollection<TblEmployeeClient> TblEmployeeClients { get; set; } = new List<TblEmployeeClient>();

        [InverseProperty("Agent")]
        public virtual ICollection<TblProperty> TblProperties { get; set; } = new List<TblProperty>();

        [ForeignKey("UserID")]
        [InverseProperty("TblEmployee")]
        public virtual TblUser User { get; set; }
    }
}