// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Core.Entities;

[Index("ClientProfileID", Name = "IX_TblFavorites_ClientProfileID")]
[Index("PropertyID", Name = "IX_TblFavorites_PropertyID")]
public partial class TblFavorite
{
    [Key]
    public int FavoriteID { get; set; }

    public int ClientProfileID { get; set; }

    public int PropertyID { get; set; }

    public DateTime? CreatedAt { get; set; }

    [ForeignKey("ClientProfileID")]
    [InverseProperty("TblFavorites")]
    public virtual TblClientProfile ClientProfile { get; set; }

    [ForeignKey("PropertyID")]
    [InverseProperty("TblFavorites")]
    public virtual TblProperty Property { get; set; }
}