// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblJobTitle
    {
        [Key]
        public int JobTitleId { get; set; }

        public string JobTitleName { get; set; }

        public string Description { get; set; }

        [InverseProperty("JobTitle")]
        public virtual ICollection<TblEmployee> TblEmployees { get; set; } = new List<TblEmployee>();
    }
}