// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    [Index("PropertyID", Name = "IX_TblPropertyImages_PropertyID")]
    public partial class TblPropertyImage
    {
        [Key]
        public int ImageID { get; set; }

        public int PropertyID { get; set; }

        public string ImagePath { get; set; }

        public DateTime? UploadedDate { get; set; }

        [ForeignKey("PropertyID")]
        [InverseProperty("TblPropertyImages")]
        public virtual TblProperty Property { get; set; }
    }
}