// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblPropertyFeature
    {
        [Key]
        public int FeatureID { get; set; }

        public string FeatureName { get; set; }

        public string Description { get; set; }

        public bool? IsAmenity { get; set; }

        public DateTime? CreatedAt { get; set; }

        [InverseProperty("Feature")]
        public virtual ICollection<TblPropertyFeaturesMapping> TblPropertyFeaturesMappings { get; set; } = new List<TblPropertyFeaturesMapping>();
    }
}