// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{
    public partial class TblPropertyDocument
    {
        [Key]
        public int DocumentID { get; set; }

        public int PropertyID { get; set; }

        public int? UserID { get; set; }

        public int DocumentTypeID { get; set; }

        public string FilePath { get; set; }

        public DateTime? UploadedAt { get; set; }

        public string Notes { get; set; }

        [ForeignKey("DocumentTypeID")]
        [InverseProperty("TblPropertyDocuments")]
        public virtual LkpDocumentType DocumentType { get; set; }

        [ForeignKey("PropertyID")]
        [InverseProperty("TblPropertyDocuments")]
        public virtual TblProperty Property { get; set; }

        [ForeignKey("UserID")]
        [InverseProperty("TblPropertyDocuments")]
        public virtual TblUser User { get; set; }
    }
}