// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Estately.Core.Entities
{

    [PrimaryKey("PropertyID", "FeatureID")]
    [Table("TblPropertyFeaturesMapping")]
    [Index("FeatureID", Name = "IX_TblPropertyFeaturesMapping_FeatureID")]
    public partial class TblPropertyFeaturesMapping
    {
        [Key]
        public int PropertyID { get; set; }

        [Key]
        public int FeatureID { get; set; }

        public string Value { get; set; }

        [ForeignKey("FeatureID")]
        [InverseProperty("TblPropertyFeaturesMappings")]
        public virtual TblPropertyFeature Feature { get; set; }

        [ForeignKey("PropertyID")]
        [InverseProperty("TblPropertyFeaturesMappings")]
        public virtual TblProperty Property { get; set; }
    }
}