// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Estately.Core.Entities;

[Index("UserTypeID", Name = "IX_TblUsers_UserTypeID")]
public partial class TblUser
{
    [Key]
    public int UserID { get; set; }

    public int? UserTypeID { get; set; }

    public string Email { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public DateTime? CreatedAt { get; set; }

    [InverseProperty("User")]
    public virtual TblClientProfile TblClientProfile { get; set; }

    [InverseProperty("User")]
    public virtual TblDeveloperProfile TblDeveloperProfile { get; set; }

    [InverseProperty("User")]
    public virtual TblEmployee TblEmployee { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<TblPropertyDocument> TblPropertyDocuments { get; set; } = new List<TblPropertyDocument>();

    [InverseProperty("User")]
    public virtual ICollection<TblPropertyHistory> TblPropertyHistories { get; set; } = new List<TblPropertyHistory>();

    [ForeignKey("UserTypeID")]
    [InverseProperty("TblUsers")]
    public virtual LkpUserType UserType { get; set; }
}